# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7830a342d1a8e9cb8ba8634bd87140480fc73d158715cc69461c2bf97028316972012e29c6aefe5a9e49438da0617ea5520744748b83b113972250fe16f87ac3

test:
  secret_key_base: 731bf00e9d316e01277ca0aa7e3fa8185cba0349ef6c90c2b797beebe1fe935a4f9e64da3328692555960e39a493f55f0f91b72feb054b616bcef36a6a756b0d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
